// Code generated by protoc-gen-go. DO NOT EDIT.
// source: swap_resolver.proto

/*
Package swapresolver is a generated protocol buffer package.

It is generated from these files:
	swap_resolver.proto

It has these top-level messages:
	ResolveRequest
	ResolveResponse
*/
package swapresolver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResolveRequest struct {
	Hash string `protobuf:"bytes,1,opt,name=hash" json:"hash,omitempty"`
}

func (m *ResolveRequest) Reset()                    { *m = ResolveRequest{} }
func (m *ResolveRequest) String() string            { return proto.CompactTextString(m) }
func (*ResolveRequest) ProtoMessage()               {}
func (*ResolveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ResolveRequest) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type ResolveResponse struct {
	Preimage string `protobuf:"bytes,1,opt,name=preimage" json:"preimage,omitempty"`
}

func (m *ResolveResponse) Reset()                    { *m = ResolveResponse{} }
func (m *ResolveResponse) String() string            { return proto.CompactTextString(m) }
func (*ResolveResponse) ProtoMessage()               {}
func (*ResolveResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ResolveResponse) GetPreimage() string {
	if m != nil {
		return m.Preimage
	}
	return ""
}

func init() {
	proto.RegisterType((*ResolveRequest)(nil), "swapresolver.ResolveRequest")
	proto.RegisterType((*ResolveResponse)(nil), "swapresolver.ResolveResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for SwapResolver service

type SwapResolverClient interface {
	// ResolveHash is used by LND to request translation of Rhash to a pre-image.
	// the resolver may return the preimage and error indicating that there is no
	// such hash/deal
	ResolveHash(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error)
}

type swapResolverClient struct {
	cc *grpc.ClientConn
}

func NewSwapResolverClient(cc *grpc.ClientConn) SwapResolverClient {
	return &swapResolverClient{cc}
}

func (c *swapResolverClient) ResolveHash(ctx context.Context, in *ResolveRequest, opts ...grpc.CallOption) (*ResolveResponse, error) {
	out := new(ResolveResponse)
	err := grpc.Invoke(ctx, "/swapresolver.SwapResolver/ResolveHash", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for SwapResolver service

type SwapResolverServer interface {
	// ResolveHash is used by LND to request translation of Rhash to a pre-image.
	// the resolver may return the preimage and error indicating that there is no
	// such hash/deal
	ResolveHash(context.Context, *ResolveRequest) (*ResolveResponse, error)
}

func RegisterSwapResolverServer(s *grpc.Server, srv SwapResolverServer) {
	s.RegisterService(&_SwapResolver_serviceDesc, srv)
}

func _SwapResolver_ResolveHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SwapResolverServer).ResolveHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swapresolver.SwapResolver/ResolveHash",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SwapResolverServer).ResolveHash(ctx, req.(*ResolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SwapResolver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "swapresolver.SwapResolver",
	HandlerType: (*SwapResolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveHash",
			Handler:    _SwapResolver_ResolveHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "swap_resolver.proto",
}

func init() { proto.RegisterFile("swap_resolver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2e, 0x2e, 0x4f, 0x2c,
	0x88, 0x2f, 0x4a, 0x2d, 0xce, 0xcf, 0x29, 0x4b, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17,
	0xe2, 0x01, 0x09, 0xc2, 0xc4, 0x94, 0x54, 0xb8, 0xf8, 0x82, 0x20, 0xec, 0xa0, 0xd4, 0xc2, 0xd2,
	0xd4, 0xe2, 0x12, 0x21, 0x21, 0x2e, 0x96, 0x8c, 0xc4, 0xe2, 0x0c, 0x09, 0x46, 0x05, 0x46, 0x0d,
	0xce, 0x20, 0x30, 0x5b, 0x49, 0x97, 0x8b, 0x1f, 0xae, 0xaa, 0xb8, 0x20, 0x3f, 0xaf, 0x38, 0x55,
	0x48, 0x8a, 0x8b, 0xa3, 0xa0, 0x28, 0x35, 0x33, 0x37, 0x31, 0x3d, 0x15, 0xaa, 0x14, 0xce, 0x37,
	0x8a, 0xe1, 0xe2, 0x09, 0x2e, 0x4f, 0x2c, 0x80, 0x6a, 0x29, 0x12, 0xf2, 0xe1, 0xe2, 0x86, 0xb2,
	0x3d, 0x12, 0x8b, 0x33, 0x84, 0x64, 0xf4, 0x90, 0x9d, 0xa0, 0x87, 0x6a, 0xbf, 0x94, 0x2c, 0x0e,
	0x59, 0x88, 0xbd, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x7f, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xcc, 0xeb, 0x10, 0xd8, 0xde, 0x00, 0x00, 0x00,
}
